import json, re, os, sys
from urllib.request import Request, urlopen
from pathlib import Path
from ruamel.yaml import YAML

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import generate

import importlib.util
spec = importlib.util.spec_from_file_location("install_clang", Path(__file__).with_name("install-clang.py"))
install_clang = importlib.util.module_from_spec(spec)
spec.loader.exec_module(install_clang)
CLANG_CUDA_MAX = install_clang.CLANG_CUDA_MAX

updates = {}

with urlopen("https://ziglang.org/download/index.json") as r:
    zig_version = json.load(r)['master']['version']

with urlopen("https://vulkan.lunarg.com/sdk/latest/linux.txt") as r:
    updates["VULKAN_VERSION"] = r.read().decode().strip()

with urlopen("https://rocm.nightlies.amd.com/whl-multi-arch/rocm/") as r:
    updates["ROCM_VERSION"] = max(re.findall(r'rocm-(\d+\.\d+\.\d+a\d+)\.tar\.gz', r.read().decode()), key=lambda v: [*map(int, re.findall(r'\d+', v))])

with urlopen("https://developer.download.nvidia.com/compute/cuda/redist/") as r:
    index = r.read().decode()

codes = generate.cuda_codes()

cuda_versions = {}
for code in sorted(codes):
    major = f"{code[:-1]}.{code[-1]}"
    cuda_versions[code] = max(re.findall(rf'redistrib_({major}\.[0-9.]+)\.json', index), key=lambda v: [*map(int, v.split('.'))])

for code in CLANG_CUDA_MAX:
    if code not in cuda_versions:
        sys.exit(f"CLANG_CUDA_MAX has unknown CUDA code '{code}'")
for code in cuda_versions:
    if code not in CLANG_CUDA_MAX:
        sys.exit(f"No clang max set for CUDA {code} - add it to CLANG_CUDA_MAX")

def github_api(url):
    req = Request(url, headers={"User-Agent": "curl/8.0"})
    if token := os.getenv("GITHUB_TOKEN"):
        req.add_header("Authorization", f"Bearer {token}")
    return json.load(urlopen(req))

clang_versions = {}
for major in sorted(set(CLANG_CUDA_MAX.values())):
    # refs matching "llvmorg-19." are all tags of the 19 series, incl. -rcN
    refs = github_api(f"https://api.github.com/repos/llvm/llvm-project/git/matching-refs/tags/llvmorg-{major}.")
    finals = [m.groups() for ref in refs for m in [re.fullmatch(r'llvmorg-(\d+)\.(\d+)\.(\d+)', ref['ref'].split('/')[-1])] if m]
    if not finals:
        sys.exit(f"No final release found for clang {major}")
    clang_versions[major] = ".".join(max(finals, key=lambda v: [*map(int, v)]))

Path(__file__).with_name("versions.py").write_text(
    "# Generated by scripts/update-ci.py - do not edit.\n"
    f"ZIG_VERSION = {zig_version!r}\n"
    f"CUDA_VERSIONS = {cuda_versions!r}\n"
    f"CLANG_VERSIONS = {clang_versions!r}\n"
)

print(f" - ZIG_VERSION: {zig_version}")
for key, value in cuda_versions.items():
    print(f" - CUDA_VERSIONS[{key}]: {value}")
for key, value in CLANG_CUDA_MAX.items():
    print(f" - CLANG_CUDA_MAX[{key}]: {value}")
for key, value in clang_versions.items():
    print(f" - CLANG_VERSIONS[{key}]: {value}")
for key, value in updates.items():
    print(f" - {key}: {value}")

yaml = YAML()
yaml.preserve_quotes = True
yaml.default_flow_style = False
yaml.width = 4096
yaml.indent(mapping=2, sequence=4, offset=2)

for path in Path(".github/workflows").glob("*.yml"):
    with open(path, 'r') as f:
        data = yaml.load(f)

    if env := data.get('jobs', {}).get('build', {}).get('env'):
        for key, value in updates.items():
            if key in env:
                env[key] = value

    with open(path, 'w') as f:
        yaml.dump(data, f)
