# Generated by scripts/update-ci.py - do not edit.
ZIG_VERSION = '0.17.0-dev.1978+c961124d9'
CUDA_VERSIONS = {'128': '12.8.2', '129': '12.9.2', '130': '13.0.3', '134': '13.4.1'}
CLANG_VERSIONS = {'19': '19.1.7', '20': '20.1.8', '22': '22.1.8'}
