name: Build any cpu

on:
  workflow_call:
    inputs: &common_inputs
      filter:
        type: string
        default: 'cpu'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ZIG_VERSION: "0.17.0-dev.1158+1d1193aa7"

    steps:
      - uses: actions/checkout@v5

      - name: Setup Zig
        run: |
          ZIG="zig-$(uname -m)-linux-$ZIG_VERSION"
          curl -LsSf "https://zigmirror.com/$ZIG.tar.xz" | tar -Jxf- -C ~
          sudo ln -sf ~/"$ZIG"/zig /usr/bin/zig

      - name: Build ${{ inputs.filter }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
        run: cmake -DFILTER=${{ inputs.filter }} -P build.cmake

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "hf[hf_xet]"
          python scripts/upload.py ${{ vars.HF_REPO }}/${{ inputs.llamacpp_version || 'test' }}
