name: Build any windows rocm

on:
  workflow_call:
    inputs: &common_inputs
      preset:
        type: string
        default: 'x86_64-windows-rocm-gfx1100'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    env:
      ROCM_VERSION: "10.2.0a20260916"

    steps:
      - uses: actions/checkout@v5

      - name: Setup windows env
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install rocm
        env:
          PRESET: ${{ inputs.preset }}
        run: |
          $Gfx = "$env:PRESET".Split('-')[-1]
          $Rocm = switch -Regex ($Gfx) {
            ('^probe$')  { 'rocm[devel,libraries]' }
            ('^gfx\d+$') { "rocm[devel,libraries,device-$Gfx]" }
            default      { 'rocm[devel,libraries,device-all]' }
          }
          pip install --extra-index-url https://nightly.repo.amd.com/rocm/whl-next/ "$Rocm==$env:ROCM_VERSION"
          rocm-sdk init
          $Root = rocm-sdk path --root
          "ROCM_PATH=$Root" >> $env:GITHUB_ENV
          "HIP_PATH=$Root" >> $env:GITHUB_ENV
          "HIP_DEVICE_LIB_PATH=$Root\lib\llvm\amdgcn\bitcode" >> $env:GITHUB_ENV

      - name: Build ${{ inputs.preset }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN_READ }}
          PRESET: ${{ inputs.preset }}
        run: cmake --workflow --preset "$env:PRESET"

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
          VERSION: ${{ inputs.llamacpp_version || 'test' }}
        run: |
          pip install -U "huggingface_hub[hf_xet]"
          python scripts/upload.py "$env:HF_REPO/$env:VERSION"
