name: Build any sycl

on:
  workflow_call:
    inputs: &common_inputs
      filter:
        type: string
        default: 'sycl'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ONEAPI_VERSION: "2025.3"
      LEVEL_ZERO_VERSION: "1.28.2"

    steps:
      - uses: actions/checkout@v5

      - name: Install deps
        run: |
          curl -sSfL https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS.PUB |
            gpg --dearmor | sudo tee /usr/share/keyrings/oneapi.gpg > /dev/null
          echo "deb [signed-by=/usr/share/keyrings/oneapi.gpg] https://apt.repos.intel.com/oneapi all main" |
            sudo tee /etc/apt/sources.list.d/oneapi.list > /dev/null
          LEVEL_ZERO="https://github.com/oneapi-src/level-zero/releases/download/v$LEVEL_ZERO_VERSION"
          curl -sSfL "$LEVEL_ZERO/level-zero_$LEVEL_ZERO_VERSION%2Bu22.04_amd64.deb" -o level-zero.deb
          curl -sSfL "$LEVEL_ZERO/level-zero-devel_$LEVEL_ZERO_VERSION%2Bu22.04_amd64.deb" -o level-zero-devel.deb
          sudo apt-get update
          sudo apt-get install -y \
            "intel-oneapi-compiler-dpcpp-cpp-$ONEAPI_VERSION" \
            "intel-oneapi-mkl-devel-$ONEAPI_VERSION" \
            "intel-oneapi-dnnl-devel-$ONEAPI_VERSION" \
            ./level-zero.deb ./level-zero-devel.deb

      - name: Build ${{ inputs.filter }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN_READ }}
        run: |
          . /opt/intel/oneapi/setvars.sh
          cmake --workflow --preset ${{ inputs.filter }}

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "hf[hf_xet]"
          python scripts/upload.py ${{ vars.HF_REPO }}/${{ inputs.llamacpp_version || 'test' }}
