name: Build any cuda

on:
  workflow_call:
    inputs: &common_inputs
      filter:
        type: string
        default: 'x86_64-linux-cuda'
      cuda_code:
        type: string
        default: '128'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

jobs:
  build:
    runs-on: ${{ startsWith(inputs.filter, 'aarch64-') && 'ubuntu-22.04-arm' || 'ubuntu-22.04' }}
    env:
      CUDA_VERSION_128: "12.8.2"
      CUDA_VERSION_129: "12.9.2"
    steps:
      - uses: actions/checkout@v5

      - name: Select CUDA version
        run: echo "CUDA_VERSION=${CUDA_VERSION_${{ inputs.cuda_code }}}" >> "$GITHUB_ENV"

      - name: Install deps
        run: |
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-12 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-12 100
          python scripts/install-cuda.py

      - name: Build ${{ inputs.filter }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN_READ }}
        run: cmake --workflow --preset ${{ inputs.filter }}

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "hf[hf_xet]"
          python scripts/upload.py ${{ vars.HF_REPO }}/${{ inputs.llamacpp_version || 'test' }}
