name: Build any rocm

on:
  workflow_call:
    inputs: &common_inputs
      filter:
        type: string
        default: 'rocm'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      ROCM_VERSION: "7.14.0a20260618"

    steps:
      - uses: actions/checkout@v5

      - name: Install deps
        run: |
          GFX="${{ inputs.filter }}"
          GFX="${GFX##*-}"
          case "$GFX" in
          (probe) ROCM="rocm[devel,libraries]" ;;
          (gfx*)  ROCM="rocm[devel,libraries,device-${GFX}]" ;;
          (*)     ROCM="rocm[devel,libraries,device-all]" ;;
          esac
          pip install --extra-index-url https://rocm.nightlies.amd.com/whl-multi-arch/ "$ROCM==$ROCM_VERSION"
          rocm-sdk init
          echo "ROCM_PATH=$(rocm-sdk path --root)" >> "$GITHUB_ENV"

      - name: Build ${{ inputs.filter }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
        run: cmake -DFILTER=${{ inputs.filter }} -P build.cmake

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "hf[hf_xet]"
          python scripts/upload.py ${{ vars.HF_REPO }}/${{ inputs.llamacpp_version || 'test' }}
