name: Build any windows cuda

on:
  workflow_call:
    inputs: &common_inputs
      filter:
        type: string
        default: 'x86_64-windows-cuda-12-80'
      cuda_code:
        type: string
        default: '128'
      deploy:
        type: boolean
      llamacpp_repo:
        type: string
      llamacpp_version:
        type: string
      boringssl_repo:
        type: string
      boringssl_version:
        type: string

  workflow_dispatch:
    inputs: *common_inputs

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v5

      - name: Setup windows env
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Install cuda
        env:
          CUDA_CODE: ${{ inputs.cuda_code }}
        run: python scripts/install-cuda.py

      - name: Build ${{ inputs.filter }}
        env:
          LLAMACPP_REPO: ${{ inputs.llamacpp_repo }}
          LLAMACPP_VERSION: ${{ inputs.llamacpp_version }}
          BORINGSSL_REPO: ${{ inputs.boringssl_repo }}
          BORINGSSL_VERSION: ${{ inputs.boringssl_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN_READ }}
          FILTER: ${{ inputs.filter }}
        run: cmake --workflow --preset "$env:FILTER"

      - name: Deploy
        if: ${{ inputs.deploy && vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
          VERSION: ${{ inputs.llamacpp_version || 'test' }}
        run: |
          pip install -U "hf[hf_xet]"
          python scripts/upload.py "$env:HF_REPO/$env:VERSION"
