name: Release
on:
  workflow_dispatch:
    inputs:
      llamacpp_repo:
        required: false
        default: ''
        type: string
      llamacpp_version:
        required: false
        default: ''
        type: string
      write_latest:
        required: false
        default: true
        type: boolean
  schedule:
    - cron: 0 0 * * 6

permissions:
  contents: read

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      llamacpp_version: ${{ steps.tags.outputs.llamacpp_version }}
      boringssl_version: ${{ steps.tags.outputs.boringssl_version }}
      write_latest: ${{ steps.tags.outputs.write_latest }}
    steps:
      - name: Get tags
        id: tags
        env:
          GH_TOKEN: ${{ github.token }}
          LLAMACPP_INPUT: ${{ inputs.llamacpp_version }}
          EVENT_NAME: ${{ github.event_name }}
          WRITE_LATEST_INPUT: ${{ inputs.write_latest }}
        run: |
          if [ "$LLAMACPP_INPUT" ]
          then LLAMACPP_VERSION="$LLAMACPP_INPUT"
          else LLAMACPP_VERSION=$(gh api "repos/ggml-org/llama.cpp/releases?per_page=30" --jq '[.[] | select(.tag_name|test("^b[0-9]+$"))][0].tag_name')
          fi
          BORINGSSL_VERSION=$(git ls-remote --tags https://boringssl.googlesource.com/boringssl | sed -nE 's,.*/tags/(0\.[0-9]+\.0)$,\1,p' | sort | tail -n 1)
          if [ "$EVENT_NAME" = "schedule" ]
          then WRITE_LATEST="true"
          else WRITE_LATEST="$WRITE_LATEST_INPUT"
          fi
          cat <<EOF >> "$GITHUB_OUTPUT"
          llamacpp_version=$LLAMACPP_VERSION
          boringssl_version=$BORINGSSL_VERSION
          write_latest=$WRITE_LATEST
          EOF
          grep _version= "$GITHUB_OUTPUT"

  aarch64-linux-cpu:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-linux-cpu-kk
          - aarch64-linux-cpu-lk
          - aarch64-linux-cpu-mk
          - aarch64-linux-cpu-nk
          - aarch64-linux-cpu-qk
          - aarch64-linux-cpu-rk
          - aarch64-linux-cpu-sk
          - aarch64-linux-cpu-uk
          - aarch64-linux-cpu-yk
          - aarch64-linux-cpu-ml
          - aarch64-linux-cpu-ql
          - aarch64-linux-cpu-qm
          - aarch64-linux-cpu-ym
          - aarch64-linux-cpu-qn
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-linux-cpu:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-linux-cpu-kkkkk
          - x86_64-linux-cpu-lkkkk
          - x86_64-linux-cpu-mkkkk
          - x86_64-linux-cpu-qkkkk
          - x86_64-linux-cpu-ylkkk
          - x86_64-linux-cpu-qnkkk
          - x86_64-linux-cpu-qrkkk
          - x86_64-linux-cpu-klokk
          - x86_64-linux-cpu-knokk
          - x86_64-linux-cpu-krokk
          - x86_64-linux-cpu-klzkk
          - x86_64-linux-cpu-knzkk
          - x86_64-linux-cpu-krzkk
          - x86_64-linux-cpu-klzlk
          - x86_64-linux-cpu-knzlk
          - x86_64-linux-cpu-krzlk
          - x86_64-linux-cpu-klxmk
          - x86_64-linux-cpu-knxmk
          - x86_64-linux-cpu-krxmk
          - x86_64-linux-cpu-klxnk
          - x86_64-linux-cpu-knxnk
          - x86_64-linux-cpu-krxnk
          - x86_64-linux-cpu-klxpk
          - x86_64-linux-cpu-knxpk
          - x86_64-linux-cpu-krxpk
          - x86_64-linux-cpu-klxrk
          - x86_64-linux-cpu-knxrk
          - x86_64-linux-cpu-krxrk
          - x86_64-linux-cpu-knxzk
          - x86_64-linux-cpu-krxzk
          - x86_64-linux-cpu-knxzq
          - x86_64-linux-cpu-krxzq
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  aarch64-windows-cpu:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-windows-cpu-kk
          - aarch64-windows-cpu-lk
          - aarch64-windows-cpu-mk
          - aarch64-windows-cpu-nk
          - aarch64-windows-cpu-qk
          - aarch64-windows-cpu-rk
          - aarch64-windows-cpu-sk
          - aarch64-windows-cpu-uk
          - aarch64-windows-cpu-yk
          - aarch64-windows-cpu-ml
          - aarch64-windows-cpu-ql
          - aarch64-windows-cpu-qm
          - aarch64-windows-cpu-ym
          - aarch64-windows-cpu-qn
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-windows-cpu:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-windows-cpu-kkkkk
          - x86_64-windows-cpu-lkkkk
          - x86_64-windows-cpu-mkkkk
          - x86_64-windows-cpu-qkkkk
          - x86_64-windows-cpu-ylkkk
          - x86_64-windows-cpu-qnkkk
          - x86_64-windows-cpu-qrkkk
          - x86_64-windows-cpu-klokk
          - x86_64-windows-cpu-knokk
          - x86_64-windows-cpu-krokk
          - x86_64-windows-cpu-klzkk
          - x86_64-windows-cpu-knzkk
          - x86_64-windows-cpu-krzkk
          - x86_64-windows-cpu-klzlk
          - x86_64-windows-cpu-knzlk
          - x86_64-windows-cpu-krzlk
          - x86_64-windows-cpu-klxmk
          - x86_64-windows-cpu-knxmk
          - x86_64-windows-cpu-krxmk
          - x86_64-windows-cpu-klxnk
          - x86_64-windows-cpu-knxnk
          - x86_64-windows-cpu-krxnk
          - x86_64-windows-cpu-klxpk
          - x86_64-windows-cpu-knxpk
          - x86_64-windows-cpu-krxpk
          - x86_64-windows-cpu-klxrk
          - x86_64-windows-cpu-knxrk
          - x86_64-windows-cpu-krxrk
          - x86_64-windows-cpu-knxzk
          - x86_64-windows-cpu-krxzk
          - x86_64-windows-cpu-knxzq
          - x86_64-windows-cpu-krxzq
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  aarch64-freebsd-cpu:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-freebsd-cpu-kk
          - aarch64-freebsd-cpu-lk
          - aarch64-freebsd-cpu-mk
          - aarch64-freebsd-cpu-nk
          - aarch64-freebsd-cpu-qk
          - aarch64-freebsd-cpu-rk
          - aarch64-freebsd-cpu-sk
          - aarch64-freebsd-cpu-uk
          - aarch64-freebsd-cpu-yk
          - aarch64-freebsd-cpu-ml
          - aarch64-freebsd-cpu-ql
          - aarch64-freebsd-cpu-qm
          - aarch64-freebsd-cpu-ym
          - aarch64-freebsd-cpu-qn
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-freebsd-cpu:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-freebsd-cpu-kkkkk
          - x86_64-freebsd-cpu-lkkkk
          - x86_64-freebsd-cpu-mkkkk
          - x86_64-freebsd-cpu-qkkkk
          - x86_64-freebsd-cpu-ylkkk
          - x86_64-freebsd-cpu-qnkkk
          - x86_64-freebsd-cpu-qrkkk
          - x86_64-freebsd-cpu-klokk
          - x86_64-freebsd-cpu-knokk
          - x86_64-freebsd-cpu-krokk
          - x86_64-freebsd-cpu-klzkk
          - x86_64-freebsd-cpu-knzkk
          - x86_64-freebsd-cpu-krzkk
          - x86_64-freebsd-cpu-klzlk
          - x86_64-freebsd-cpu-knzlk
          - x86_64-freebsd-cpu-krzlk
          - x86_64-freebsd-cpu-klxmk
          - x86_64-freebsd-cpu-knxmk
          - x86_64-freebsd-cpu-krxmk
          - x86_64-freebsd-cpu-klxnk
          - x86_64-freebsd-cpu-knxnk
          - x86_64-freebsd-cpu-krxnk
          - x86_64-freebsd-cpu-klxpk
          - x86_64-freebsd-cpu-knxpk
          - x86_64-freebsd-cpu-krxpk
          - x86_64-freebsd-cpu-klxrk
          - x86_64-freebsd-cpu-knxrk
          - x86_64-freebsd-cpu-krxrk
          - x86_64-freebsd-cpu-knxzk
          - x86_64-freebsd-cpu-krxzk
          - x86_64-freebsd-cpu-knxzq
          - x86_64-freebsd-cpu-krxzq
    uses: ./.github/workflows/build-any-cpu.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  aarch64-linux-vulkan:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-linux-vulkan-kk
          - aarch64-linux-vulkan-lk
          - aarch64-linux-vulkan-mk
          - aarch64-linux-vulkan-nk
          - aarch64-linux-vulkan-qk
          - aarch64-linux-vulkan-rk
          - aarch64-linux-vulkan-sk
          - aarch64-linux-vulkan-uk
          - aarch64-linux-vulkan-yk
          - aarch64-linux-vulkan-ml
          - aarch64-linux-vulkan-ql
          - aarch64-linux-vulkan-qm
          - aarch64-linux-vulkan-ym
          - aarch64-linux-vulkan-qn
          - aarch64-linux-vulkan-probe
    uses: ./.github/workflows/build-any-vulkan.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-linux-vulkan:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-linux-vulkan-kkkkk
          - x86_64-linux-vulkan-lkkkk
          - x86_64-linux-vulkan-mkkkk
          - x86_64-linux-vulkan-qkkkk
          - x86_64-linux-vulkan-ylkkk
          - x86_64-linux-vulkan-qnkkk
          - x86_64-linux-vulkan-qrkkk
          - x86_64-linux-vulkan-klokk
          - x86_64-linux-vulkan-knokk
          - x86_64-linux-vulkan-krokk
          - x86_64-linux-vulkan-klzkk
          - x86_64-linux-vulkan-knzkk
          - x86_64-linux-vulkan-krzkk
          - x86_64-linux-vulkan-klzlk
          - x86_64-linux-vulkan-knzlk
          - x86_64-linux-vulkan-krzlk
          - x86_64-linux-vulkan-klxmk
          - x86_64-linux-vulkan-knxmk
          - x86_64-linux-vulkan-krxmk
          - x86_64-linux-vulkan-klxnk
          - x86_64-linux-vulkan-knxnk
          - x86_64-linux-vulkan-krxnk
          - x86_64-linux-vulkan-klxpk
          - x86_64-linux-vulkan-knxpk
          - x86_64-linux-vulkan-krxpk
          - x86_64-linux-vulkan-klxrk
          - x86_64-linux-vulkan-knxrk
          - x86_64-linux-vulkan-krxrk
          - x86_64-linux-vulkan-knxzk
          - x86_64-linux-vulkan-krxzk
          - x86_64-linux-vulkan-knxzq
          - x86_64-linux-vulkan-krxzq
          - x86_64-linux-vulkan-probe
    uses: ./.github/workflows/build-any-vulkan.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  aarch64-windows-vulkan:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-windows-vulkan-kk
          - aarch64-windows-vulkan-lk
          - aarch64-windows-vulkan-mk
          - aarch64-windows-vulkan-nk
          - aarch64-windows-vulkan-qk
          - aarch64-windows-vulkan-rk
          - aarch64-windows-vulkan-sk
          - aarch64-windows-vulkan-uk
          - aarch64-windows-vulkan-yk
          - aarch64-windows-vulkan-ml
          - aarch64-windows-vulkan-ql
          - aarch64-windows-vulkan-qm
          - aarch64-windows-vulkan-ym
          - aarch64-windows-vulkan-qn
          - aarch64-windows-vulkan-probe
    uses: ./.github/workflows/build-any-vulkan.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-windows-vulkan:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-windows-vulkan-kkkkk
          - x86_64-windows-vulkan-lkkkk
          - x86_64-windows-vulkan-mkkkk
          - x86_64-windows-vulkan-qkkkk
          - x86_64-windows-vulkan-ylkkk
          - x86_64-windows-vulkan-qnkkk
          - x86_64-windows-vulkan-qrkkk
          - x86_64-windows-vulkan-klokk
          - x86_64-windows-vulkan-knokk
          - x86_64-windows-vulkan-krokk
          - x86_64-windows-vulkan-klzkk
          - x86_64-windows-vulkan-knzkk
          - x86_64-windows-vulkan-krzkk
          - x86_64-windows-vulkan-klzlk
          - x86_64-windows-vulkan-knzlk
          - x86_64-windows-vulkan-krzlk
          - x86_64-windows-vulkan-klxmk
          - x86_64-windows-vulkan-knxmk
          - x86_64-windows-vulkan-krxmk
          - x86_64-windows-vulkan-klxnk
          - x86_64-windows-vulkan-knxnk
          - x86_64-windows-vulkan-krxnk
          - x86_64-windows-vulkan-klxpk
          - x86_64-windows-vulkan-knxpk
          - x86_64-windows-vulkan-krxpk
          - x86_64-windows-vulkan-klxrk
          - x86_64-windows-vulkan-knxrk
          - x86_64-windows-vulkan-krxrk
          - x86_64-windows-vulkan-knxzk
          - x86_64-windows-vulkan-krxzk
          - x86_64-windows-vulkan-knxzq
          - x86_64-windows-vulkan-krxzq
          - x86_64-windows-vulkan-probe
    uses: ./.github/workflows/build-any-vulkan.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  aarch64-linux-cuda:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        include:
          - filter: aarch64-linux-cuda-75
            cuda_code: '128'
          - filter: aarch64-linux-cuda-80
            cuda_code: '128'
          - filter: aarch64-linux-cuda-86
            cuda_code: '128'
          - filter: aarch64-linux-cuda-89
            cuda_code: '128'
          - filter: aarch64-linux-cuda-90
            cuda_code: '128'
          - filter: aarch64-linux-cuda-100
            cuda_code: '128'
          - filter: aarch64-linux-cuda-120
            cuda_code: '128'
          - filter: aarch64-linux-cuda-121
            cuda_code: '129'
          - filter: aarch64-linux-cuda-probe
            cuda_code: '129'
    uses: ./.github/workflows/build-any-linux-cuda.yml
    with:
      filter: ${{ matrix.filter }}
      cuda_code: ${{ matrix.cuda_code }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-linux-cuda:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        include:
          - filter: x86_64-linux-cuda-75
            cuda_code: '128'
          - filter: x86_64-linux-cuda-80
            cuda_code: '128'
          - filter: x86_64-linux-cuda-86
            cuda_code: '128'
          - filter: x86_64-linux-cuda-89
            cuda_code: '128'
          - filter: x86_64-linux-cuda-90
            cuda_code: '128'
          - filter: x86_64-linux-cuda-100
            cuda_code: '128'
          - filter: x86_64-linux-cuda-120
            cuda_code: '128'
          - filter: x86_64-linux-cuda-121
            cuda_code: '129'
          - filter: x86_64-linux-cuda-probe
            cuda_code: '129'
    uses: ./.github/workflows/build-any-linux-cuda.yml
    with:
      filter: ${{ matrix.filter }}
      cuda_code: ${{ matrix.cuda_code }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-windows-cuda:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        include:
          - filter: x86_64-windows-cuda-12-75
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-80
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-86
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-89
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-90
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-100
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-120
            cuda_code: '128'
          - filter: x86_64-windows-cuda-12-121
            cuda_code: '129'
          - filter: x86_64-windows-cuda-13-75
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-80
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-86
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-89
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-90
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-100
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-120
            cuda_code: '130'
          - filter: x86_64-windows-cuda-13-121
            cuda_code: '130'
          - filter: x86_64-windows-cuda-probe
            cuda_code: '129'
    uses: ./.github/workflows/build-any-windows-cuda.yml
    with:
      filter: ${{ matrix.filter }}
      cuda_code: ${{ matrix.cuda_code }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  x86_64-linux-rocm:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - x86_64-linux-rocm-gfx906
          - x86_64-linux-rocm-gfx90a
          - x86_64-linux-rocm-gfx942
          - x86_64-linux-rocm-gfx950
          - x86_64-linux-rocm-gfx1030
          - x86_64-linux-rocm-gfx1031
          - x86_64-linux-rocm-gfx1032
          - x86_64-linux-rocm-gfx1011
          - x86_64-linux-rocm-gfx1100
          - x86_64-linux-rocm-gfx1101
          - x86_64-linux-rocm-gfx1102
          - x86_64-linux-rocm-gfx1103
          - x86_64-linux-rocm-gfx1150
          - x86_64-linux-rocm-gfx1151
          - x86_64-linux-rocm-gfx1152
          - x86_64-linux-rocm-gfx1153
          - x86_64-linux-rocm-gfx1200
          - x86_64-linux-rocm-gfx1201
          - x86_64-linux-rocm-probe
    uses: ./.github/workflows/build-any-rocm.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  aarch64-macos-metal:
    name: ${{ matrix.filter }}
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        filter:
          - aarch64-macos-metal-m1
          - aarch64-macos-metal-m2
          - aarch64-macos-metal-m3
          - aarch64-macos-metal-m4
          - aarch64-macos-metal-m5
          - aarch64-macos-metal-a18
    uses: ./.github/workflows/build-any-metal.yml
    with:
      filter: ${{ matrix.filter }}
      deploy: true
      llamacpp_repo: ${{ inputs.llamacpp_repo }}
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      boringssl_version: ${{ needs.init.outputs.boringssl_version }}
    secrets: inherit
  release:
    runs-on: ubuntu-latest
    needs:
      - init
      - aarch64-linux-cpu
      - x86_64-linux-cpu
      - aarch64-windows-cpu
      - x86_64-windows-cpu
      - aarch64-freebsd-cpu
      - x86_64-freebsd-cpu
      - aarch64-linux-vulkan
      - x86_64-linux-vulkan
      - aarch64-windows-vulkan
      - x86_64-windows-vulkan
      - aarch64-linux-cuda
      - x86_64-linux-cuda
      - x86_64-windows-cuda
      - x86_64-linux-rocm
      - aarch64-macos-metal
    steps:
      - uses: actions/checkout@v5

      - name: Upload artefacts
        if: ${{ vars.HF_REPO != '' }}
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
          VERSION: ${{ needs.init.outputs.llamacpp_version }}
        run: |
          pip install -U "hf[hf_xet]"
          python scripts/fetch-artefacts.py
          python scripts/upload.py "$HF_REPO/$VERSION"
          rm -rf output

  test:
    needs:
      - init
      - release
    if: ${{ vars.HF_REPO != '' }}
    uses: ./.github/workflows/test-release.yml
    with:
      llamacpp_version: ${{ needs.init.outputs.llamacpp_version }}
      write_latest: ${{ needs.init.outputs.write_latest == 'true' }}
    secrets: inherit
