name: Test release

on:
  pull_request:
  workflow_dispatch:
    inputs: &inputs
      llamacpp_version:
        required: false
        default: ''
        type: string
      write_latest:
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs: *inputs

permissions:
  contents: read

jobs:
  test:
    name: Test (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            runner: ubuntu-latest
            install: sh install.sh
            llama: ~/.llama-app/llama

          - platform: windows
            runner: windows-latest
            install: pwsh install.ps1
            llama: llama.exe

          - platform: macos
            runner: macos-latest
            install: sh install.sh
            llama: ~/.llama-app/llama
    steps:
      - uses: actions/checkout@v5

      - name: Install
        env:
          LLAMA_BUCKET: ${{ vars.HF_REPO }}
          LLAMA_VERSION: ${{ inputs.llamacpp_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: ${{ matrix.install }}

      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: ${{ matrix.llama }} bench -v -hf ggml-org/test-model-stories260K

  latest:
    runs-on: ubuntu-latest
    needs:
      - test
    if: ${{ vars.HF_REPO != '' && inputs.write_latest == true && inputs.llamacpp_version != '' }}
    steps:
      - uses: actions/checkout@v5

      - name: Write latest file
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_REPO: ${{ vars.HF_REPO }}
          VERSION: ${{ inputs.llamacpp_version }}
        run: |
          pip install -U "huggingface_hub[hf_xet]"
          mkdir output
          printf '%s' "$VERSION" > output/latest
          python scripts/upload.py "$HF_REPO"
