name: Test release

on:
  pull_request:
  workflow_dispatch:
    inputs: &inputs
      llamacpp_version:
        required: false
        default: ''
        type: string
      write_latest:
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs: *inputs

jobs:
  test:
    name: Test (${{ matrix.platform }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux
            runner: ubuntu-latest
            install: sh install.sh
            llama: ~/.llama-app/llama

          - platform: windows
            runner: windows-latest
            install: pwsh install.ps1
            llama: llama.exe

          - platform: macos
            runner: macos-latest
            install: sh install.sh
            llama: ~/.llama-app/llama
    steps:
      - uses: actions/checkout@v5

      - name: Install
        env:
          LLAMA_BUCKET: ${{ vars.HF_REPO }}
          LLAMA_VERSION: ${{ inputs.llamacpp_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: ${{ matrix.install }}

      - name: Test
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: ${{ matrix.llama }} bench -v -hf ggml-org/test-model-stories260K

  test-no-zstd:
    name: Test (linux, no zstd)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Hide zstd
        run: |
          ZSTD=$(command -v zstd) && sudo mv "$ZSTD" /tmp/zstd.disabled
          ! command -v zstd

      - name: Install
        env:
          LLAMA_BUCKET: ${{ vars.HF_REPO }}
          LLAMA_VERSION: ${{ inputs.llamacpp_version }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: sh install.sh

      - name: Check downloaded binaries
        run: |
          for FILE in ~/.llama-app/*; do
            head -c 4 "$FILE" | od -An -tx1 | tr -d ' \n' | grep -qx 7f454c46 ||
              { printf "%s: not an ELF binary\n" "$FILE" >&2; exit 1; }
          done

  latest:
    runs-on: ubuntu-latest
    needs:
      - test
      - test-no-zstd
    if: ${{ vars.HF_REPO != '' && inputs.write_latest == true && inputs.llamacpp_version != '' }}
    steps:
      - uses: actions/checkout@v5

      - name: Write latest file
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          pip install -U "hf[hf_xet]"
          mkdir output
          printf "${{ inputs.llamacpp_version }}" > output/latest
          python scripts/upload.py ${{ vars.HF_REPO }}
